const IndiaData = {
  Maharashtra: {
    // Pune Division
    Pune: [
      "Haveli",
      "Mulshi",
      "Baramati",
      "Bhor",
      "Daund",
      "Khed",
      "Maval",
      "Pune City",
      "Shirur",
      "Junnar",
      "Ambegaon",
      "Indapur",
      "Purandar",
      "Saswad",
    ],

    Satara: [
      "Satara",
      "Karad",
      "Khandala",
      "Phaltan",
      "Wai",
      "Mahabaleshwar",
      "Panchgani",
      "Dahiwadi",
      "Koregaon",
      "Man",
    ],
    Sangli: [
      "Sangli",
      "Miraj",
      "Kadepur",
      "Palus",
      "Jat",
      "Khanapur",
      "Atpadi",
      "Tasgaon",
      "Vita",
      "Mhaswad",
    ],
    Kolhapur: [
      "Kolhapur",
      "Karvir",
      "Hatkanangale",
      "Kagal",
      "Radhanagari",
      "Panhala",
      "Gadhinglaj",
      "Ajra",
      "Shahuwadi",
      "Bhudargad",
    ],
    Solapur: [
      "Solapur City",
      "Barshi",
      "Karmala",
      "Mangalvedhe",
      "Mohol",
      "Pandharpur",
      "Sangola",
      "South Solapur",
      "North Solapur",
    ],
    // Konkan Division
    Mumbai: [
      "Mumbai City",
      "Mumbai Suburban",
      "Dharavi",
      "Ghatkopar",
      "Andheri",
      "Bandra",
      "Dadar",
      "Malad",
      "Borivali",
      "Kandivali",
      "Versova",
      "Juhu",
      "Sion",
      "Worli",
      "Marine Lines",
      "Colaba",
    ],

    Mumbai_Suburban: [
      "Andheri",
      "Borivali",
      "Dahisar",
      "Ghatkopar",
      "Kandivali",
      "Malad",
      "Mahalaxmi",
      "Mulund",
      "Powai",
      "Sion",
      "Vile Parle",
      "Versova",
      "Bandra",
      "Dadar",
      "Juhu",
      "Khar",
    ],
    Thane: [
      "Thane",
      "Kalyan",
      "Dombivli",
      "Bhiwandi",
      "Mira-Bhayandar",
      "Vasai",
      "Palghar",
      "Ambarnath",
      "Ulhasnagar",
      "Maharashtra Nagar",
      "Shahapur",
      "Wada",
      "Murbad",
      "Khadakpada",
    ],
    Palghar: [
      "Palghar",
      "Vasai",
      "Virar",
      "Dahanu",
      "Boisar",
      "Wada",
      "Maharashtra Nagar",
      "Talasari",
      "Jawhar",
      "Dahisar",
    ],
    Raigad: [
      "Alibag",
      "Pen",
      "Karjat",
      "Matheran",
      "Uran",
      "Panvel",
      "Khalapur",
      "Mahad",
      "Roha",
      "Tala",
    ],
    Ratnagiri: [
      "Ratnagiri",
      "Dapoli",
      "Khed",
      "Guhagar",
      "Chiplun",
      "Mandangad",
      "Rajapur",
      "Lanja",
    ],
    Sindhudurg: [
      "Sindhudurg",
      "Malvan",
      "Kankavli",
      "Devgad",
      "Vengurla",
      "Sawantwadi",
      "Kudal",
      "Nivara",
    ],

    // Nashik Division

    Nandurbar: [
      "Nandurbar",
      "Shahada",
      "Taloda",
      "Akkalkuwa",
      "Nandurbar City",
      "Navapur",
      "Dhadgaon",
    ],
    Jalgaon: [
      "Jalgaon",
      "Bhadgaon",
      "Chopda",
      "Erandol",
      "Yawal",
      "Muktainagar",
      "Raver",
      "Parola",
    ],
    Dhule: [
      "Dhule",
      "Shindkheda",
      "Sakri",
      "Sindkheda",
      "Nandurbar",
      "Dondaicha",
      "Khadki",
      "Pimpalgaon",
    ],

    Ahmednagar: [
      "Ahmednagar",
      "Akole",
      "Parner",
      "Shirpur",
      "Kopargaon",
      "Rahuri",
      "Sangamner",
      "Nevasa",
      "Pathardi",
      "Jamkhed",
    ],
    Nashik: [
      "Nashik",
      "Nashik City",
      "Dindori",
      "Sinnar",
      "Igatpuri",
      "Trimbak",
      "Malegaon",
      "Kalwan",
      "Deola",
      "Baglan",
    ],
  

  // Aurangabad (Chhatrapati Sambhajinagar) Division
  Aurangabad_Ch_Sambhajinagar: [
    "Aurangabad",
    "Kannad",
    "Soegaon",
    "Sillod",
    "Phulambri",
    "Khuldabad",
    "Vaijapur",
    "Gangapur",
    "Paithan",
  ],
  Jalna: [
    "Jalna",
    "Ambad",
    "Bhokardan",
    "Badnapur",
    "Mantha",
    "Partur",
    "Ghansawangi",
  ],
  Beed: [
    "Beed",
    "Georai",
    "Ashti",
    "Patoda",
    "Majalgaon",
    "Parli",
    "Kaij",
    "Ambejogai",
    "Wadwani",
    "Shirur (Kasar)",
  ],
  Osmanabad_Dharashiv: [
    "Osmanabad",
    "Tuljapur",
    "Omerga",
    "Paranda",
    "Kalamb",
    "Lohara",
    "Bhoom",
    "Vashi",
  ],
  Latur: [
    "Latur",
    "Ausa",
    "Nilanga",
    "Renapur",
    "Ahmedpur",
    "Chakur",
    "Shirur Anantpal",
    "Deoni",
    "Udgir",
  ],
  Nanded: [
    "Nanded",
    "Hadgaon",
    "Kinwat",
    "Bhokar",
    "Deglur",
    "Mukhed",
    "Kandhar",
    "Loha",
    "Himayatnagar",
    "Umri",
    "Ardhapur",
    "Mahur",
  ],
  Hingoli: ["Hingoli", "Sengaon", "Kalamnuri", "Basmath"],
  Parbhani: [
    "Parbhani",
    "Gangakhed",
    "Pathri",
    "Jintur",
    "Sonpeth",
    "Palam",
    "Purna",
    "Manwath",
    "Sailu",
  ],

  //   Amravati Division

  Amravati: [
    "Amravati",
    "Achalpur",
    "Chandur Bazar",
    "Daryapur",
    "Chikhaldara",
    "Morshi",
    "Warud",
    "Nandgaon Khandeshwar",
    "Anjangaon Surji",
    "Bhatkuli",
    "Teosa",
  ],
  Akola: [
    "Akola",
    "Balapur",
    "Barshitakli",
    "Murtizapur",
    "Patur",
    "Telhara",
    "Akot",
  ],
  Buldhana: [
    "Buldhana",
    "Chikhli",
    "Deulgaon Raja",
    "Khamgaon",
    "Mehkar",
    "Malkapur",
    "Motala",
    "Jalgaon Jamod",
    "Sangrampur",
    "Lonar",
    "Nandura",
    "Sindkhed Raja",
  ],
  Washim: ["Washim", "Risod", "Mangrulpir", "Karanja", "Malegaon", "Manora"],
  Yavatmal: [
    "Yavatmal",
    "Pusad",
    "Umarkhed",
    "Ghatanji",
    "Digras",
    "Kalamb",
    "Wani",
    "Arni",
    "Ralegaon",
    "Ner",
    "Babhulgaon",
    "Mahagaon",
    "Zari Jamani",
  ],

  //   Nagpur Division
  Nagpur: [
    "Nagpur (Urban)",
    "Nagpur (Rural)",
    "Hingna",
    "Kamptee",
    "Umred",
    "Katol",
    "Narkhed",
    "Parseoni",
    "Ramtek",
    "Savner",
    "Kalameshwar",
    "Bhiwapur",
  ],
  Wardha: [
    "Wardha",
    "Seloo",
    "Deoli",
    "Hinganghat",
    "Arvi",
    "Ashti",
    "Karanja (Ghadge)",
    "Samudrapur",
  ],
  Bhandara: [
    "Bhandara",
    "Tumsar",
    "Mohadi",
    "Pauni",
    "Sakoli",
    "Lakhani",
    "Lakhandur",
  ],
  Gondia: [
    "Gondia",
    "Tirora",
    "Goregaon",
    "Amgaon",
    "Salekasa",
    "Sadak Arjuni",
    "Arjuni Morgaon",
  ],
  Chandrapur: [
    "Chandrapur",
    "Ballarpur",
    "Warora",
    "Bramhapuri",
    "Chimur",
    "Mul",
    "Nagbhid",
    "Pombhurna",
    "Rajura",
    "Saoli",
    "Sindewahi",
    "Gondpipri",
    "Korpana",
    "Jiwati",
  ],
  Gadchiroli: [
    "Gadchiroli",
    "Armori",
    "Desaiganj (Vadasa)",
    "Chamorshi",
    "Sironcha",
    "Aheri",
    "Mulchera",
    "Etapalli",
    "Kurkheda",
    "Korchi",
    "Bhamragad",
  ],
},

  Gujarat: {
    Ahmedabad: ["Daskroi", "Sanand", "Dholka"],
    Surat: ["Choryasi", "Bardoli", "Palsana"],
  },
  Karnataka: {
    Bengaluru: ["Bangalore South", "Bangalore North", "Yelahanka"],
    Mysuru: ["Nanjangud", "T. Narasipura", "Hunsur"],
  },
};

export default IndiaData;
